# -*- coding: utf-8 -*-
"""cie-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dd68dBHm74o5fdviEhr6AnBnczBKFjUy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

data=pd.read_csv("/content/Mall_Customers2.csv")
print (data.head())
data.info()

data.isnull().sum
data.describe()

x=data.iloc[:,[3,4]].values

wcss_list= []
for i in range(1, 11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state= 42)
  kmeans.fit(x)
  wcss_list.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss_list)
plt.title('The Elobw Method Graph')
plt.xlabel('Number of clusters(k)')
plt.ylabel('wcss_list')
plt.show()

optimal_clusters=5
kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_predict=kmeans.fit_predict(x)

plt.scatter(x[y_predict==0,0],x[y_predict==0,1],s=100,c='blue',label='cluster1')
plt.scatter(x[y_predict==1,0],x[y_predict==1,1],s=100,c='pink',label='cluster2')
plt.scatter(x[y_predict==2,0],x[y_predict==2,1],s=100,c='green',label='cluster3')
plt.scatter(x[y_predict==3,0],x[y_predict==3,1],s=100,c='red',label='cluster4')
plt.scatter(x[y_predict==4,0],x[y_predict==4,1],s=100,c='orange',label='cluster5')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='yellow',label='centroid')
plt.title('Clusters of customers')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.legend()
plt.show()